name: Build hi6250-phenix
on:
  workflow_dispatch:
jobs:
  build:

    name: Build hi6250_Kernelsu_phenixkernel-${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: install dependencies
      run: |
        sudo apt install gcc-7 gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi
        sudo apt install binutils make python libssl-dev build-essential bc  bison flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git -y
        
    - name: Download kernel source
      run: |
        sudo -i
        cd $GITHUB_WORKSPACE
        git clone -b phenix-1.0 https://github.com/chen2021-web/android_kernel_huawei_hi6250.git
        cd android_kernel_huawei_hi6250

    - name: Build Kernel
      working-directory: android_kernel_huawei_hi6250
      run: |
       sudo -i
       export ARCH=arm64
       export SUBARCH=arm64
       make O=out  phenix_defconfig ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi-
       make O=out  -j$(nproc --all) ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi-
    - name: check
      run: |
       cd /home/runner/work/github-action-build-kernel/github-action-build-kernel/android_kernel_huawei_hi6250/out/arch/arm64/boot/
       ls
    - name: Upload boot directory
      uses: actions/upload-artifact@v3
      with:
        name: boot
        path: /home/runner/work/github-action-build-kernel/github-action-build-kernel/android_kernel_huawei_hi6250/out/arch/arm64/boot
      
